Signup page flag / iss98
moevm/mse_auto_checking_slides_vaganov pull request #103
Opened 2021-06-17 13:57 UTC by kinekt2000

- [x] Создан механизм блокирования запросов по условию
- [x] Добавлен флаг SIGNUP_PAGE_ENABLED в .env
- [ ] Удалена ссылка со страницы авторизации

2021-06-17 19:50 UTC, kinekt2000 commented
Также добавил docker-compose-dev.yml для создания dev контейнера, который могу менять на горячую. При необходимости закину в .gitignore.

2021-06-19 07:11 UTC, HadronCollider requested changes
- Оставил комментарии по коду
- `docker-compose-dev` - ок, давно стоило его добавить

2021-06-19 07:13 UTC, HadronCollider commented
P.S. По готовности задачи/PR к review - перемещайте в соответствующий столбец (https://github.com/moevm/mse_auto_checking_slides_vaganov/projects/2)

2021-06-24 17:27 UTC, HadronCollider approved these changes

2021-06-24 17:28 UTC, merged