Version page / iss84
moevm/mse_auto_checking_slides_vaganov pull request #112
Opened 2021-06-24 13:57 UTC by kinekt2000

- [x] Скрипт для генерация данных о текущей версии
- [x] Создание файла с данными о текущей версии
- [x] Загрузка данных о текущей версии в приложение
- [x] Страница /version
- [x] Ссылка на страницу из навигации админа

scripts/version.sh - выводит данные о версии
в scripts/restart.sh добавлены инструкции для создания файла с данными о версии
в scripts/restart.sh можно определить название генерируемого файла
файл с данными о текущей версии создается в корне проекта, после чего помещается в образ.

2021-06-24 17:42 UTC, HadronCollider requested changes

2021-06-24 17:42 UTC, HadronCollider commented on Dockerfile
> +CMD python3.8 ./app/server.py -d
Для деплоя нужен ключ -p (чтобы отключить DEBUG режим flask'a)

2021-06-24 17:42 UTC, HadronCollider commented on app/settings.py
> +    VERSION_DATA = { "error": str(error) }
Многовато try/except на квадратный метр - лучше перед `open(version_file)` проверяйте `os.path.isfile(version_file)` (внутренний try/except для json parse error - ok)

2021-06-24 17:42 UTC, HadronCollider commented on docker-compose-dev.yml
> +version: '2'
У нас уже есть https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/dev/docker-compose-dev.yml
А это что за покемон?

2021-06-24 17:42 UTC, HadronCollider commented on templates/header.html
> +            {% if name == "admin" %}
На то, что пользователь - админ указывает поле `is_admin` у пользователя.
Кажется, шаблонизатор имеет доступ к переменной `current_user` (в которой хранится объект класса [User](https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/dev/app/bd_helper/bd_types.py#L13))
Если не имеет, но оставьте так + создайте задачу по этой проблеме

2021-06-24 18:01 UTC, HadronCollider commented
+ добавьте исполняемым sh-файлам соответствующие права (chmod +x)

2021-06-24 18:04 UTC, kinekt2000 commented
> * добавьте исполняемым sh-файлам соответствующие права (chmod +x)

Не догнал. Прописать chmod +x version.sh перед исполнением в restart?

2021-06-24 18:07 UTC, kinekt2000 commented on docker-compose-dev.yml
> +version: '2'
Этот покемон в dev попал из моей другой ветки. А мне эта штука везде нужна была.

2021-06-24 18:49 UTC, HadronCollider commented
> > * добавьте исполняемым sh-файлам соответствующие права (chmod +x)
> 
> Не догнал. Прописать chmod +x version.sh перед исполнением в restart?

Нет, необходимо у себя локально сделать `chmod +x version.sh` и запушить эти изменения (гит должен подхватывать подобные изменения), иначе сейчас запуск файла будет выдавать `Permission denied`, т.к. файл не содержит прав на выполнение.

2021-06-24 18:51 UTC, HadronCollider commented on docker-compose-dev.yml
> +version: '2'
Попробуйте стянуть изменения из dev - иначе сейчас при мерже мы получим два `docker-compose-dev.yml` файла

2021-06-24 18:55 UTC, kinekt2000 commented
> > > * добавьте исполняемым sh-файлам соответствующие права (chmod +x)
> > 
> > 
> > Не догнал. Прописать chmod +x version.sh перед исполнением в restart?
> 
> Нет, необходимо у себя локально сделать `chmod +x version.sh` и запушить эти изменения (гит должен подхватывать подобные изменения), иначе сейчас запуск файла будет выдавать `Permission denied`, т.к. файл не содержит прав на выполнение.

Вроде как все права и так выданы, либо я что-то не понимаю. В любом случае у меня chmod ничего не меняет
![image](https://user-images.githubusercontent.com/42917151/123317544-d1382500-d536-11eb-90d9-77bb7c5c2df9.png)
Может быть это из-за того, что у меня wsl

2021-06-24 19:02 UTC, futurewarning commented
> Вроде как все права и так выданы, либо я что-то не понимаю. В любом случае у меня chmod ничего не меняет

git update-index --chmod=+x version.sh + коммит или что-то типа того

2021-06-24 19:17 UTC, kinekt2000 commented
Вроде как сделал

2021-06-25 08:10 UTC, kinekt2000 commented on docker-compose-dev.yml
> +version: '2'
Сделано

2021-06-25 10:33 UTC, kinekt2000 commented
Я тут немного посмотрел на то, что написал и мне не нравится как оно выглядит. Решение проблемы через if/else мне не особо симпатизирует, однако и вложенные try/except тоже не круто.
Поэтому возможен следующий вариант:
```python
try:
    with open(version_file) as vfp:
        json_string = vfp.read()
        VERSION_DATA = json.loads(json_string)
except JSONDecodeError as error:
    VERSION_DATA = {
        "error": str(error),
        "data": error.doc
    }
except IOError as error:
    VERSION_DATA = {"error": f"{error.strerror}: {error.filename}"}
except Exception as error:
    VERSION_DATA = { "error": repr(error) }
```

2021-06-25 10:53 UTC, HadronCollider commented
> Я тут немного посмотрел на то, что написал и мне не нравится как оно выглядит. Решение проблемы через if/else мне не особо симпатизирует, однако и вложенные try/except тоже не круто.
> Поэтому возможен следующий вариант:
> 
> ```python
> try:
>     with open(version_file) as vfp:
>         json_string = vfp.read()
>         VERSION_DATA = json.loads(json_string)
> except JSONDecodeError as error:
>     VERSION_DATA = {
>         "error": str(error),
>         "data": error.doc
>     }
> except IOError as error:
>     VERSION_DATA = {"error": f"{error.strerror}: {error.filename}"}
> except Exception as error:
>     VERSION_DATA = { "error": repr(error) }
> ```

Такой подход прекрасен с точки зрения отлова исключений - прописывание вероятных и кастомной обработкой каждого (это не вложенные try/except) - если хотите можете поправить (а я только собрался мержить PR...). Но помните про адекватные и человекочитаемые сообщения об ошибках

2021-06-25 11:00 UTC, kinekt2000 commented
> Но помните про адекватные и человекочитаемые сообщения об ошибках

Вот так это выглядит, на деле ничего не поменялось.
Если это IO ошибки, то выведет сообщение и путь до файла
![image](https://user-images.githubusercontent.com/42917151/123415020-5108d280-d5bd-11eb-8556-5216f8f28a49.png)

Если JSONDecode, то выводит ошибку, указывает на нее в файле и дублирует содержимое.
![image](https://user-images.githubusercontent.com/42917151/123415181-8ca39c80-d5bd-11eb-8a70-be66726cefdd.png)

Внешне ничего не изменилось, а код куда менее ступенчатый

2021-06-25 11:35 UTC, HadronCollider approved these changes

2021-06-25 11:36 UTC, merged