Table features / iss85
moevm/mse_auto_checking_slides_vaganov pull request #116
Opened 2021-06-29 20:16 UTC by kinekt2000

### front:
- [x] сортировка
- [x] фильтры
- [x] пагинация
- [x] запись в адресную строку
- [x] запрос на сервер
________________________________________

### back:
- [x] запрос для страницы
- [x] запрос для данных
- [ ] пагинация запроса данных
- [ ] фильтрация запроса данных
- [ ] сортировка запроса данных

2021-06-30 14:55 UTC, kinekt2000 commented on app/server.py
> +        rows = rows.find({"user": current_user.username})
@HadronCollider 
Сижу, пытаюсь делать фильтры для запроса и словил себя на том, что это ужасно выглядит. Есть варианты, как придать этому более удобоваримую форму.

2021-06-30 15:38 UTC, HadronCollider commented on app/server.py
> +        rows = rows.find({"user": current_user.username})
@kinekt2000 
Мой код с другого проекта: https://pastebin.com/wGNP9ZCa 
там использовался монго-движок, поэтому есть конструкции вида `Solutions.objects.raw`, но конструкция аналогична `checks_collection.find`.
Попробуйте разобраться, будут вопросы - пишите (звоните)

2021-07-01 09:19 UTC, kinekt2000 commented
@HadronCollider 
![image](https://user-images.githubusercontent.com/42917151/124099354-19d76d00-da66-11eb-9d86-25b0f481407a.png)
Пока выглядит как-то вот-так. Title и Username фильтруются регулярным выражением, т.е. необязательно вводить полностью. Фильтровать id по регулярному выражению не догоняю как, ведь это не строка, а объект `ObjectId`. Нужно ли вообще фильтровать по id?
Что необходимо изменить во внешнем виде кроме того, что столбец id сделать ссылками?

2021-07-01 10:54 UTC, HadronCollider commented
- фильтрация по id не нужна (бессмысленна), кроме того, вы всё равно используете фильтрацию по _id при фильтрации по времени
- внешний вид в целом ок

---
- Расскажите, как посмотреть вашу таблицу, если у меня после сборки/запуска всё вот так:
![image](https://user-images.githubusercontent.com/21632402/124111893-704aa880-da72-11eb-925e-7842cf870b34.png)

2021-07-01 10:56 UTC, kinekt2000 commented
@HadronCollider 
А, ну я это все отдельно сделал и не буду удалять и менять то, что было до меня, пока все не будет готово.
Открыть страницу можно только вручную прописав в адресной строке /check_list

2021-07-01 10:58 UTC, HadronCollider commented
А как я мог что-то увидеть, если не сказали 😡

2021-07-01 10:59 UTC, HadronCollider commented on Dockerfile
> +FROM ubuntu:18.04
Поправьте это изменение (уберите его)

Суть в изменении LF на CRLF

2021-07-01 11:01 UTC, HadronCollider commented on app/server.py
> +    get_all_checks, get_user_checks, format_stats, format_check, checks_collection)
Лучше сделайте отдельный метод в bd*, который будет получать query/limit/offset (по аналогии с тем, что я кидал) - код для работы с БД стоит размещать в соответствующем модуле

2021-07-01 11:07 UTC, kinekt2000 commented on app/server.py
> +        f_upload_date_list = list(filter(lambda val: val, f_upload_date.split("-")))
Дата может представлять собой промежуток, разделенный символом '-'. Если строка запроса представляет собой сто-то типа '01.01.2021-', то split разобьет строку на две подстроки - ["01.01.2021", ""], этот фильтр убирает пустые строки. 
Та же история со score.

2021-07-01 11:08 UTC, kinekt2000 commented on app/server.py
> +        f_upload_date_list = list(filter(lambda val: val, f_upload_date.split("-")))
скорее всего позже я это перепишу как-нибудь иначе.

2021-07-01 11:08 UTC, HadronCollider commented on app/server.py
> +    sort = sort if sort in ["_id", "filename", "user", "upload-date", "score"] else None
Насколько необходимо проверять, что sort (и order ниже) принимают какие-то определенные значения?

Но если всё же захотите оставить, то
- захардкорженные значения при изменении модели БД придётся изменять, что весьма неудобно
- если указывать в python что-то захаркорженные лучше использовать tuple

2021-07-01 11:13 UTC, HadronCollider commented on app/server.py
> +            "upload-date": item["_id"].generation_time.strftime("%d.%m.%Y"),
Добавьте также время (часы/минуты) при отображении - вести поиск по ним не требуется, но в таблице показывать стоит

2021-07-01 11:20 UTC, kinekt2000 commented on app/server.py
> +    sort = sort if sort in ["_id", "filename", "user", "upload-date", "score"] else None
Делаю подобную проверку, т.к. в документации ничего не написано, что будет, если вызвать sort для несуществующего поля. Такой хардкод используется т.к. далеко не все поля используются.

2021-07-01 11:31 UTC, kinekt2000 commented on app/server.py
> +    sort = sort if sort in ["_id", "filename", "user", "upload-date", "score"] else None
Только что проверил, если всякий мусор залетает в sort или order, то ничего не падает. Так что уберу.

2021-07-01 17:41 UTC, kinekt2000 commented
@HadronCollider 
Поправил всякие штуки
Теперь выглядит вот так:
![image](https://user-images.githubusercontent.com/42917151/124166859-0a7b1280-daac-11eb-80e5-c9b5d17a5ec3.png)
Но пока не считаю доделанным. Надо в html еще футер добавить, а хедере меню вставить и фоновый цвет откорректировать.
Мне еще шрифт не нравится, но вроде как везде такой.

2021-07-02 12:49 UTC, kinekt2000 commented
В общем-то готово. Есть только один нерешенный вопрос. Сейчас все это дело находится в /check_list. Нужно ли мне переименовывать мое, или поменять ссылку в пункте меню "Статистика".

2021-07-02 12:53 UTC, kinekt2000 commented
Пользователь с включенными фильтрами
![image](https://user-images.githubusercontent.com/42917151/124277006-3ac6bd80-db4d-11eb-9953-f9948e315913.png)

Пользователь с выключенными фильтрами
![image](https://user-images.githubusercontent.com/42917151/124277049-47e3ac80-db4d-11eb-8382-5c1235042276.png)

Админ с включенными фильтрами
![image](https://user-images.githubusercontent.com/42917151/124277236-7eb9c280-db4d-11eb-93ae-b99d351be94d.png)

Админ с выключенными фильтрами
![image](https://user-images.githubusercontent.com/42917151/124277293-8bd6b180-db4d-11eb-9208-c06da3199848.png)

2021-07-02 12:58 UTC, kinekt2000 commented
Пагинацию всегда можно потестить на маленькой выборке результатов, указав в адресной строке параметр size
![image](https://user-images.githubusercontent.com/42917151/124277927-4a92d180-db4e-11eb-885a-b66818870428.png)

2021-07-02 12:59 UTC, HadronCollider commented
Поменяйте ссылку "Статистика" в меню

2021-07-02 13:02 UTC, kinekt2000 commented
> Поменяйте ссылку "Статистика" в меню

Сделано

2021-07-02 13:57 UTC, HadronCollider commented
- удалил из кода старую таблицу (чтобы не смущала)
- добавил параметр при рендере check_list, чтобы на странице была ссылка на загрузку презентаций

2021-07-02 14:07 UTC, HadronCollider requested changes
Пара багов:
1. Параметры фильтрации сохраняются к URL, однако при обновлении страницы они попадают - так быть не должно
  - После установки фильтров:
http://127.0.0.1:8080/check_list?page=1&size=5&filter=%7B%22upload-date%22%3A%2202.07.2021-03.07.2021%22%7D&sort=upload-date&order=desc
![image](https://user-images.githubusercontent.com/21632402/124285871-09eb8600-db57-11eb-8a62-9a3601f03e33.png)

  - После перезагрузки: в URI что-то похожее на фильтры есть, но пропали значения для sort, а формат `upload-date` отличается от первоначального, значения фильтрации остаются в поле ввода, однако уже никак не учитываются при загрузке данных (01.07 в таблице):
http://127.0.0.1:8080/check_list?page=1&size=5&filter%5Bupload-date%5D=02.07.2021-03.07.2021&sort=&order=
![image](https://user-images.githubusercontent.com/21632402/124285950-1e2f8300-db57-11eb-9d13-33cfb34faa85.png)

  - После ещё одной перезагрузки - фильтрации нет совсем: ни параметров URI, ни параметров в полях ввода
http://127.0.0.1:8080/check_list?page=1&size=5&filter=&sort=&order=
![image](https://user-images.githubusercontent.com/21632402/124285983-25569100-db57-11eb-9397-796b2e3c32cd.png)


2. Не совсем понятно как работает фильтрации по одной дате:
  - установлено 02.07.2021 - данных нет (хотя проверки 02.07 были)
![image](https://user-images.githubusercontent.com/21632402/124286395-91d19000-db57-11eb-8a7f-cbfb7d5b4c14.png)
  - установлено 03.07.2021 (проверок очевидно нет)
![image](https://user-images.githubusercontent.com/21632402/124286478-aa41aa80-db57-11eb-98dc-c8c2e58e951c.png)
  - установлено 02.07-03.07 - вылезли все имеющиеся проверки
![image](https://user-images.githubusercontent.com/21632402/124286549-c1809800-db57-11eb-840a-9f49aafe1676.png)

Кажется, при одной указанной дате стоит использовать что-то вроде
`{'$gte': time, '$lte': time + timedelta(days=1)}` (в вашем случае, это будет ObjectID для разных дат), поскольку данная конструкция `ObjectId.from_datetime(datetime.strptime(f_upload_date_list[0], "%d.%m.%Y"))` сделает вам дату "день.месяц.год 00:00:00" - поиск будет вестись для проверок с именно таким временем

2021-07-02 16:19 UTC, kinekt2000 commented
Ну вроде как работает

2021-07-05 12:59 UTC, HadronCollider requested changes
Всё ещё есть баг с сохранением фильтров - https://youtu.be/C6Q2xoLQlUU

При переходе на страницу с фильтрами и добавлением нового - старый при перезагрузке сбрасывается

2021-07-05 14:18 UTC, kinekt2000 commented
Когда-нибудь я смогу оседлать эти фильтры. Из-за того, что это расширение, оно очень плохо стакается со стандартными функциями. Отсюда такие проблемы.

2021-07-06 10:37 UTC, HadronCollider requested changes
https://youtu.be/se6FeMSyJLE

- основная новая проблема - невозможно сбросить фильтры: удаление из полей ввода не меняет URL, так же, как и `Clear filters`
- сбрасывается сортировка при перезагрузке ([0:14](https://youtu.be/se6FeMSyJLE?t=14))

2021-07-06 10:42 UTC, HadronCollider commented
В другом проекте пару лет назад у нас было что-то около: [url_by_filter.js](https://pastebin.com/vMFHRh7g)
Там без расширений + не уверен как работает с большими строками, но вдруг поможет (или нет)

2021-07-06 13:18 UTC, kinekt2000 commented
У меня тут какие-то лютые проблемы с кнопкой "очистить фильтры". Она чистит фильтры только если в какой-то из них был совершен ввод руками.
Если я пытаюсь приделать в наглую обработчик на нажатие кнопки, чтоб очистить поля, то функция-констурктор запроса все равно вызывается до того, как отрабатывает событие клика по кнопке, а значит все значения полей ввода попадают в запрос.

2021-07-06 13:28 UTC, kinekt2000 commented
Проще наверное ее вообще убрать

2021-07-06 19:11 UTC, HadronCollider commented
Видос записывать лень, но сортировка по дате не работает :с

2021-07-06 19:38 UTC, kinekt2000 commented
Я ща с ума сойду

2021-07-06 20:00 UTC, HadronCollider commented
Я уже

2021-07-07 07:31 UTC, kinekt2000 commented
Теперь сортировка работает

2021-07-07 07:32 UTC, HadronCollider commented
Точно работает? Я ж пойду сейчас проверю...

2021-07-07 07:33 UTC, kinekt2000 commented
сортировка работает, за остальное не отвечаю :)

2021-07-07 07:59 UTC, merged