pdf
moevm/mse_auto_checking_slides_vaganov pull request #160
Opened 2021-09-09 14:28 UTC by futurewarning

2021-09-14 16:40 UTC, HadronCollider requested changes
- Оставил комментарии по коду
- Поехали ссылки:
![image](https://user-images.githubusercontent.com/21632402/133298624-15bfed54-6954-4b39-9e05-9c443847320e.png)

2021-09-14 16:40 UTC, HadronCollider commented on app/servants/data.py
> +        check(parse(filename), checks, presentation_name, current_user.username, converted_id)
Передавать внутрь метода `check` `converted_id` = идти в разрез с логикой и целью функции (она проверяет презентацию - причем тут её пдф-версия?) + в итоге использование нового добавленного аргумента сводится к
```
checks.conv_pdf_fs_id = pdf_id`
```

Явно стоит этот id записывать в объект проверки до/после вызова проверки

2021-09-14 16:40 UTC, HadronCollider commented on templates/results.html
> +        <a href ="/get_pdf/{{ id }}" id="pdf" class="col text-center">PDF</a>
Давайте использовать функцию `url_for` от flask (в шаблонах она доступна) - принимает string-название функции (если функция в Blueprint, то `<blueprint_name>.<method>`), которая обёрнута нужным нам роутом, и именованные аргументы для запроса
```
href="{{url_for("get_pdf", _id=id)}}"	# получится нечто похожее на это
```
По возможности поменяйте и роуты выше - это избавит от необходимости вручную переписывать роуты в шаблоне в случае изменения пути роута.

2021-09-16 07:36 UTC, HadronCollider requested changes
- В случае, если у проверки нет pdf (старые решения) - стоит убирать ссылку `PDF` на странице результатов (кажется, в шаблон передается `result` класса Check, в котором есть/нет поле `convert_pdf_id`, указывающее на то, есть ли для этой презентации PDF)
- Ссылки "скачать"/"pdf" не исправились

2021-09-16 13:35 UTC, futurewarning commented
![Screenshot from 2021-09-16 16-18-08](https://user-images.githubusercontent.com/36329275/133621622-e2db6b0d-4ccf-40ac-98eb-b5d5ec61be84.png)

2021-09-19 15:18 UTC, merged

2021-09-20 10:15 UTC, HadronCollider reviewed
Done