criteria from conf
moevm/mse_auto_checking_slides_vaganov pull request #162
Opened 2021-09-12 22:38 UTC by futurewarning

2021-09-14 16:56 UTC, HadronCollider commented
Аналогично https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/161#pullrequestreview-754205944

2021-09-14 16:56 UTC, HadronCollider requested changes
Аналогично https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/161#pullrequestreview-754205944

2021-09-15 16:54 UTC, futurewarning commented
http://e.moevm.info/mod/lti/view.php?id=1544, с зависимостью на #161, slides_number: [10, 12] -> bsc, [13, 15] -> msc; detect_additional=True/False меняет вердикты в случае превышения числа слайдов(T возвращает число учитывая регулярку для запасных сладов с сообщением о проверке запасных, F - общее число слайдов и превышение границ)

2021-09-20 10:12 UTC, HadronCollider approved these changes
Done

2021-09-20 10:13 UTC, merged