add docx_parser (#212)
moevm/mse_auto_checking_slides_vaganov pull request #218
Opened 2022-03-06 18:36 UTC by jendos2001

2022-03-06 19:10 UTC, Augiro747 requested changes

2022-03-06 19:10 UTC, Augiro747 commented on app/main/mse22/docx/core_properties.py
> +        print()
Замени на метод to_string(), который будет возвращать строку с текстовым представлением объекта - это более универсально

2022-03-06 19:10 UTC, Augiro747 commented on app/main/mse22/docx/paragraph.py
> +        print()
Аналогично

2022-03-07 19:21 UTC, jendos2001 commented on app/main/mse22/docx/core_properties.py
> +        print()
Исправил

2022-03-07 19:21 UTC, jendos2001 commented on app/main/mse22/docx/paragraph.py
> +        print()
Исправил

2022-03-08 10:07 UTC, Augiro747 requested changes

2022-03-08 10:07 UTC, Augiro747 commented on app/main/mse22/docx/core_properties.py
> +        print(df.to_string())
метод должен называться to_string и возвращать(return) строку вместо принта, в остальном всё ок, просто строку потом отдельно можно в print вбить, поэтому так удобнее

2022-03-08 10:07 UTC, Augiro747 commented on app/main/mse22/docx/paragraph.py
> +        print(df.to_string())
аналогично

2022-03-09 17:59 UTC, jendos2001 commented on app/main/mse22/docx/core_properties.py
> +        print(df.to_string())
Пофиксил

2022-03-09 17:59 UTC, jendos2001 commented on app/main/mse22/docx/paragraph.py
> +        print(df.to_string())
Пофиксил

2022-03-10 09:17 UTC, Augiro747 approved these changes

2022-03-10 09:18 UTC, merged