refactored
moevm/mse_auto_checking_slides_vaganov pull request #248
Opened 2022-04-19 14:05 UTC by ghettodimasta

2022-04-24 08:53 UTC, Mi-ch-ael approved these changes
Работоспособность проверена. Работает для .odt и .doc. Если передать (например, по ошибке) файл .docx, тоже отработает нормально.

2022-04-24 18:23 UTC, ghettodimasta commented
Добавил PdfDocumentManager

2022-04-24 20:24 UTC, Mi-ch-ael requested changes
Добавить инструкцию по запуску в README.

2022-04-25 14:18 UTC, Mi-ch-ael requested changes
Добавить используемый пакет pdfplumber в зависимости.

2022-04-26 09:39 UTC, Mi-ch-ael approved these changes

2022-04-29 10:08 UTC, merged