page objects
moevm/mse_auto_checking_slides_vaganov pull request #256
Opened 2022-04-23 04:05 UTC by dmitrikuz

2022-04-26 17:07 UTC, Mi-ch-ael requested changes

2022-04-26 17:07 UTC, Mi-ch-ael commented on app/main/mse22/document/page_object.py
> +        self.data_matrix = [[c.text for c in row.cells] for row in table.rows]
Нам потребуются все абзацы внутри ячейки, чтобы проверять форматирование таблиц (это атрибут `paragraphs`). То есть `c.paragraphs` вместо `c.text`.

2022-04-30 08:53 UTC, Mi-ch-ael approved these changes

2022-04-30 09:58 UTC, VictorHegel commented
closes #247

2022-04-30 09:58 UTC, merged