pagecounter
moevm/mse_auto_checking_slides_vaganov pull request #331
Opened 2022-06-22 16:39 UTC by oorschnai

2022-06-23 13:37 UTC, HadronCollider requested changes
- Пофиксите оставшиеся файлы с измененными флагами (на гитхабе помечены `100644 → 100755`)
- См. комментарии ниже

2022-06-23 13:37 UTC, HadronCollider commented on app/main/checks/report_checks/page_counter.py
> +        return answer(False, f'Неверное количество страниц в файле. ({count} страниц)')
Сделайте сообщение в случае провала более понятным для пользователя - добавьте указание проверяемых границ ("требуемое количество [x,y]. В отчете {count}"), чтобы было ясно в какую сторону нужно "идти" для исправлений

2022-06-23 13:37 UTC, HadronCollider commented on app/main/checks/report_checks/page_counter.py
> +        print(type(self.file.paragraphs[0]))
Не используйте print-ы (они печатаются в stdout и не сохраняются), если печатаемые сообщения/логи необходимы, воспользуйтесь logger-ом
```python3
from root_logger import get_root_logger
logger = get_root_logger('web')
...
logger.debug(...)
logger.info(...)
```

2022-06-23 14:05 UTC, oorschnai commented
Исправила

2022-06-24 13:59 UTC, HadronCollider approved these changes
Ок, PR вмержу позднее с #330
Можете приступать к следующим задачам

2022-07-06 12:51 UTC, HadronCollider requested changes
Нужен небольшой фикс: чтобы не подгонять под разные числа окончания `страница/страниц` и сделать сообщение более приятным - сделайте используйте сокращение `стр.`
![image](https://user-images.githubusercontent.com/21632402/177553946-7b1f446d-687b-409f-8b98-c29dbd0d342f.png)

2022-07-09 11:58 UTC, oorschnai commented
Готово

2022-07-10 09:19 UTC, HadronCollider approved these changes

2022-07-10 09:19 UTC, merged