Literature references search
moevm/mse_auto_checking_slides_vaganov pull request #343
Opened 2022-07-03 10:01 UTC by oorschnai

2022-07-09 11:59 UTC, oorschnai commented
Готово

2022-07-10 09:33 UTC, oorschnai commented
Конфликты решены

2022-07-10 09:52 UTC, HadronCollider requested changes
Что-то пошло не так 
![image](https://user-images.githubusercontent.com/21632402/178139810-8c3ae352-6cf6-44dc-af74-d80b57a8854d.png)

Возможно из-за наличия ссылки на несуществующий источник `[5]` - такое тоже стоит отслеживать и сообщать

2022-07-10 10:17 UTC, oorschnai commented
Исправила

2022-07-10 10:20 UTC, HadronCollider approved these changes

2022-07-10 10:20 UTC, merged