Added table and image references counter
moevm/mse_auto_checking_slides_vaganov pull request #394
Opened 2023-04-15 13:34 UTC by poiqwq

Added 2 criteria and fixed others

2023-04-17 14:28 UTC, poiqwq commented
All is ready for check

2023-04-17 17:04 UTC, HadronCollider requested changes

2023-04-17 17:04 UTC, HadronCollider commented on app/main/checks/report_checks/style_check_settings.py
> +        "first_line_indent_cm": 1.25,
У меня в этом месте возникали проблемы с проверкой отступа первой строки (поэтому ставил 0) - если баг ушел, то ок

2023-04-18 06:46 UTC, HadronCollider approved these changes

2023-04-18 06:46 UTC, merged