Auto conversion of old formats into new
moevm/mse_auto_checking_slides_vaganov pull request #402
Opened 2023-04-25 21:36 UTC by Saprigenie

2023-06-28 09:25 UTC, HadronCollider requested changes

2023-06-28 09:25 UTC, HadronCollider commented on app/tasks.py
> +        updated_check = check(parsed_files, check_obj)
Не стоит выносить логику удаления дубликата сюда (с учетом, что через пару строк опять идет удаление файлов, но уже оригинальных), если мы хотим "подменить" старый файл на новый - стоит это делать в функции парсинга

2023-06-28 09:25 UTC, HadronCollider commented on app/main/parser.py
>  def parse(filepath):
- из комментария выше - удаляйте ненужный файл (старого формата) в этой функции
    - останется одно возвращаемое значение 
- добавьте сообщение в лог, что файл старого формата и преобразован в новый
- преобразуйте функцию, чтобы в ней был один return (так будет проще всё отслеживать и модифицировать)

2023-06-28 16:51 UTC, Saprigenie commented on app/tasks.py
> +        updated_check = check(parsed_files, check_obj)
Исправил, теперь удаление временных файлов происходит в парсере.

2023-07-03 17:51 UTC, HadronCollider approved these changes

2023-07-03 17:51 UTC, merged