424 visualize max value
moevm/mse_auto_checking_slides_vaganov pull request #438
Opened 2023-05-28 14:32 UTC by MarinaProsche

Изменение файла "app/templates/upload.html"
В форме наравне с допустимыми форматами отображается максимальный возможный объем для загружаемого файла.

2023-06-05 11:23 UTC, HadronCollider requested changes

2023-06-05 11:23 UTC, HadronCollider commented on app/templates/upload.html
> +                                        Формат: pdf (объем не больше {{ config.MAX_CONTENT_LENGTH//1024//1024 }} Mб.)</label>
Загрузка файла (в том числе с отдельным PDF = загрузка двух файлов) ) пока работает по логике "суммарный объем не более MAX_CONTENT_LENGTH"

Поэтому кажется лучше добавить или отдельное примечание (по типу "Общий объем загружаемых файлов должен составлять не более ...") или общую для обеих форм фразу, по которой будет понятно, что нельзя приложить 16+16, но можно только Х+У=16

2023-06-13 08:03 UTC, MarinaProsche commented on app/templates/upload.html
> +                                        Формат: pdf (объем не больше {{ config.MAX_CONTENT_LENGTH//1024//1024 }} Mб.)</label>
Исправила. Новый вариант:

https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/424_visualize_max_value/app/templates/upload.html

2023-06-20 09:30 UTC, HadronCollider approved these changes
Немного пофиксил/украсил/добавил, что увидел

2023-06-20 09:36 UTC, merged