430 and 435 info max value
moevm/mse_auto_checking_slides_vaganov pull request #439
Opened 2023-05-28 14:54 UTC by MarinaProsche

Кастомизация сообщения об ошибке, когда загружаемый материал больше чем максимально разрешенный объем (Issue #430 и #435)

2023-06-05 11:36 UTC, HadronCollider approved these changes

2023-06-05 11:36 UTC, HadronCollider commented on app/templates/upload.html
>                              <div id="uploading_form" class="custom-file">
Старайтесь не смешивать разные задачи/PR из других PR - этот файл изменен в рамках другой задачи/PR, в которые необходимо внести изменения (после ревью) - в перспективе это может сулить merge conflicts, когда у нас появляется один файл, изменяемый параллельно в двух местах

2023-06-05 11:36 UTC, HadronCollider commented on assets/scripts/upload.js
> +        label.html(`Формат: pptx (объем не больше ${file_upload_limit / 1024 / 1024} Мб.)`);
`Формат: pptx` - загружаться могут не только файлы формата pptx, поэтому сделайте текст сообщения общим
+ к тексту сообщения - https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/438#discussion_r1217928377


Кроме того, pdf_file_input - это поле для PDF

2023-06-05 11:36 UTC, HadronCollider commented on assets/scripts/upload.js
> +    let file_limit = file_upload_limit/1024/1024
Кажется, у вас уже есть переменная file_limit в 17 строке - если не ошибаюсь, она должна быть тут доступна

2023-06-05 11:36 UTC, HadronCollider commented on assets/scripts/upload.js
> +        label.html(`Формат: pptx (объем не больше ${file_upload_limit / 1024 / 1024} Мб.)`);
Аналогично про `Формат: pptx`

2023-06-05 11:36 UTC, HadronCollider commented on assets/scripts/upload.js
> +    let file_limit = file_upload_limit/1024/1024
Чтобы не дублировать код (для file_input и pdf_file_input, ранее это было сделано в качестве хотфикса) - попробуйте вынести логику в отдельную функцию - тогда понадобится меньше кода и исправлений текста сообщений, в случае необходимости

2023-06-05 11:37 UTC, HadronCollider requested changes
Ошибся кнопкой :)

Комментарии для исправления выше

2023-06-13 08:01 UTC, MarinaProsche commented on assets/scripts/upload.js
> +    let file_limit = file_upload_limit/1024/1024
Исправила, новый вариант:

https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/430_and_435_info_max_value/assets/scripts/upload.js

2023-06-20 09:56 UTC, HadronCollider approved these changes

2023-06-20 09:57 UTC, merged