add empty_slide_check
moevm/mse_auto_checking_slides_vaganov pull request #445
Opened 2023-06-02 14:56 UTC by MarinaProsche

Добавлен критерий проверки пустых слайдов в презентации. Файл "empty_slide_check"

2023-06-05 11:44 UTC, HadronCollider requested changes

2023-06-05 11:44 UTC, HadronCollider commented on app/main/checks/presentation_checks/empty_slide_check.py
> +                empty_pages.append(page)
Придумал более интересный код для подобной логики (ещё и однострочный, мы всё-таки в python + list comprehension работает быстрее) - посмотрите/изучите код ниже (спросите, если не понятно) и замените
```python3
empty_pages = [page for page, slide in enumerate(self.file.get_text_from_slides(), 1) if not slide.strip()]
```

2023-06-05 11:44 UTC, HadronCollider commented on app/main/checks/presentation_checks/empty_slide_check.py
> +                'Не пройдена, обнаружены пустые слайды: {}'.format(', '.join(map(str, empty_pages)))))
Метод `format_page_link` возвращает список строк, поэтому использование map+str избыточно

+ можно написать сразу (без сохранения в переменную)
`', '.join(self.format_page_link(empty_pages))`

2023-06-13 08:23 UTC, MarinaProsche commented on app/main/checks/presentation_checks/empty_slide_check.py
> +                'Не пройдена, обнаружены пустые слайды: {}'.format(', '.join(map(str, empty_pages)))))
Все поняла, все исправила:

https://github.com/moevm/mse_auto_checking_slides_vaganov/blob/432_empty_slide/app/main/checks/presentation_checks/empty_slide_check.py

2023-06-20 10:35 UTC, HadronCollider requested changes
Неверный результат: 
![image](https://github.com/moevm/mse_auto_checking_slides_vaganov/assets/21632402/ed858ee3-f02d-4c80-af12-92d04f6ea735)

Проверял прикрепленном файле (там три вида пустого слайда)
[Презентация_ВКР_Борисовский — копия.pptx](https://github.com/moevm/mse_auto_checking_slides_vaganov/files/11798986/_._.pptx)

2023-07-05 19:38 UTC, MarinaProsche commented
Исправила.
Новый вариант:
https://github.com/moevm/mse_auto_checking_slides_vaganov/commit/0aee23a221e3b4fc89c655116e83ec9cbf71953e

2023-07-07 07:01 UTC, MarinaProsche commented
Заменила поиск страницы на регулярное выражение, чтобы, если номер страницы совпадет с числом из текста на слайде, из строки удалялась именно страница.

https://github.com/moevm/mse_auto_checking_slides_vaganov/commit/c69166ae8f52d7c0f0fddd709c474ff28d8a9f3b

2023-07-30 17:17 UTC, HadronCollider approved these changes

2023-07-30 17:18 UTC, merged