add min and max border lit_references
moevm/mse_auto_checking_slides_vaganov pull request #448
Opened 2023-06-05 08:07 UTC by MarinaProsche

Добавлен кретерий-параметр количества литературы (минимальный и максимальный)
Реализуется после проверки существующего источника на другие ошибки.

2023-07-30 17:55 UTC, HadronCollider requested changes
См. комментарии

В остальном - окей

2023-07-30 17:55 UTC, HadronCollider commented on app/main/checks/report_checks/literature_references.py
> +            else:
Сделайте общую проверку на вхождение в диапазон (тогда информационное сообщение можно будет сделать одно общее и в коде меньше if/else)

2023-07-31 13:19 UTC, MarinaProsche commented
Исправила.

https://github.com/moevm/mse_auto_checking_slides_vaganov/commit/5a846f5095243f9371a2117c5b4165fdd294c5a0

2023-10-31 18:57 UTC, dart-mih requested changes

2023-10-31 18:57 UTC, dart-mih commented on app/main/checks/report_checks/literature_references.py
> +            if self.max_ref < number_of_sources < self.min_ref:
Данное условие никогда не выполнится:
Например, при max_ref = 10000, min_ref = 5 и number_of_source = 3: 10000< 3<5 будет false; и при number_of_source = 7: 10000< 7 < 5 будет тоже false.
- Полагаю, нужно поменять местами max_ref и min_ref(ИЛИ развернуть знаки), чтобы true возвращалось, когда number_of_source попадает в диапазон (значит, проверка пройдена) и false, когда не попадает (выводить сообщение об этом)

2023-11-08 08:16 UTC, MarinaProsche commented on app/main/checks/report_checks/literature_references.py
> +            if self.max_ref < number_of_sources < self.min_ref:
Исправила.

2023-11-08 21:59 UTC, dart-mih approved these changes

2023-11-17 08:25 UTC, merged