Spelling check criteria for reports
moevm/mse_auto_checking_slides_vaganov pull request #450
Opened 2023-06-08 21:33 UTC by Saprigenie

2023-06-28 09:39 UTC, HadronCollider requested changes

2023-06-28 09:39 UTC, HadronCollider commented on app/main/checks/report_checks/spelling_check.py
> +    def __init__(self, file_info, errors_count=4, scale_with_num_of_pages=True):
В качестве параметров оценивания для критерия используйте диапазон (условно min/max) для ошибок во всём документа
- если меньше min - 1 балл
- если в [min, max] - дробный балл обратно пропорциональный ошибкам
- если больше max - 0 баллов

2023-06-28 09:39 UTC, HadronCollider commented on app/main/checks/report_checks/spelling_check.py
> +        self.spell_checker = LanguageTool('ru-RU')
Если есть какое-то сравнение производительности / оценка работы для найденных инструментов (https://github.com/moevm/mse_auto_checking_slides_vaganov/issues/358#issuecomment-1583030468) - вынесите ну отдельную вики страницу

2023-06-29 18:12 UTC, Saprigenie commented on app/main/checks/report_checks/spelling_check.py
> +    def __init__(self, file_info, errors_count=4, scale_with_num_of_pages=True):
Добавлен диапазон с возможностью получения дробного балла.

2023-06-29 23:23 UTC, Saprigenie commented on app/main/checks/report_checks/spelling_check.py
> +        self.spell_checker = LanguageTool('ru-RU')
Добавлена страница в вики с сравнением инструментов:
https://github.com/moevm/mse_auto_checking_slides_vaganov/wiki/%D0%A1%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%80%D0%B5%D0%B4%D1%81%D1%82%D0%B2-%D0%B4%D0%BB%D1%8F-%D0%BF%D0%BE%D0%B8%D1%81%D0%BA%D0%B0-%D0%BE%D1%80%D1%84%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85-%D0%BE%D1%88%D0%B8%D0%B1%D0%BE%D0%BA.

2023-07-03 18:08 UTC, HadronCollider approved these changes

2023-07-03 18:09 UTC, merged