373 page with criteria
moevm/mse_auto_checking_slides_vaganov pull request #460
Opened 2023-08-12 12:18 UTC by MarinaProsche

Добавлен первый вариант таблицы с информацией о критериях.

2023-11-09 00:03 UTC, dart-mih requested changes

2023-11-09 00:03 UTC, dart-mih commented on app/server.py
> +        check_labels_and_discrpt = {CRITERIA_LABELS[check[0]]: CRITERIA_DESCRIPTION[check[0]] for check in list_of_check}
На этой строчке при запуске с базовыми критериями презентаций падает по KeyError.
Есть подозрения, что там ниже описаны не все критерии

2023-11-13 18:52 UTC, MarinaProsche commented on app/server.py
> +        check_labels_and_discrpt = {CRITERIA_LABELS[check[0]]: CRITERIA_DESCRIPTION[check[0]] for check in list_of_check}
https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/460/commits/6724db136ad84882700ca45b2d7d72aa574a4610

Исправила.

2024-02-19 23:16 UTC, HadronCollider approved these changes

2024-02-19 23:17 UTC, merged