Fix button lab report
moevm/mse_auto_checking_slides_vaganov pull request #462
Opened 2023-09-19 15:33 UTC by MarinaProsche

Исправлен баг: кнопка после загрузки файла лабобраторной работы на сайт становится активной.

2023-09-21 13:27 UTC, HadronCollider requested changes

2023-09-21 13:27 UTC, HadronCollider commented on app/main/check_packs/pack_config.py
Старайтесь не пушить локальные фиксы/комментарии в репозиторий, чтобы не "засорять" код для деплоя (откатите или просто вручную удалите изменения)

2023-09-21 13:27 UTC, HadronCollider commented on app/servants/pre_luncher.py
Аналогично с app/main/check_packs/pack_config.py

2023-09-22 08:28 UTC, MarinaProsche commented on app/main/check_packs/pack_config.py
вручную удалила.

2023-09-22 08:29 UTC, MarinaProsche commented on app/servants/pre_luncher.py
вручную удалила

2023-11-09 10:33 UTC, dart-mih commented
Полагаю, этот pull request пустой (0 строк изменений)?
Если в нем не планируется исправления бага с кнопкой, то надо просто его закрыть

2023-11-09 10:33 UTC, dart-mih commented
Прошу прощения, сам случайно и закрыл) 
Оставлю выбор за вами

2023-11-17 08:25 UTC, closed without merging