481 first selenium test
moevm/mse_auto_checking_slides_vaganov pull request #482
Opened 2023-12-12 12:25 UTC by MarinaProsche

Добавлена папка "tests", сделаны первые варианты тестов для авторизации согласно заданию
https://github.com/moevm/mse_auto_checking_slides_vaganov/issues/481
в файле tests/README.md пояснения к работе с библиотеками и браузером

2023-12-23 08:52 UTC, zmm commented on tests/main.py
> +    host_arg = 'http://127.0.0.1:8080'
Нужно вынести адрес тестируемого хоста в параметры командной строки main.py

2023-12-23 08:54 UTC, zmm commented on tests/test_authorization.py
> +        self.check_auth(os.environ['ADMIN_PASSWORD'], os.environ['ADMIN_PASSWORD'])
Тут навверное ожидался логин и пароль (сейчас два раза пароль)?

2023-12-23 08:54 UTC, zmm commented on tests/main.py
> +            param=host))
Кажется, здесь не хватает передачи логина и пароля в класс для теста (сам логин и пароль нужно тоже сделать параметрами командной строки main.py)

2023-12-29 15:34 UTC, MarinaProsche commented on tests/main.py
> +    host_arg = 'http://127.0.0.1:8080'
сделано

2023-12-29 15:35 UTC, MarinaProsche commented on tests/main.py
> +            param=host))
Исправила.

2024-02-20 14:04 UTC, HadronCollider requested changes
Добавил пару мелких комментариев, в остальном отлично

2024-02-20 14:04 UTC, HadronCollider commented on requirements.txt
> +webdriver-manager==4.0.1
Вынесите зависимости для тестов в отдельный `tests/requirements.txt`
- зависимости для них в основном контейнере системы не нужны
- инструкция в readme станет полегче (подготовка сократится до `pip install -r`)

2024-02-20 14:04 UTC, HadronCollider commented on tests/README.md
> +## For beginning:
Добавьте пункт про установку firefox - я оказался тем самым человеком, у которого его нет:)

2024-02-20 14:06 UTC, HadronCollider commented
Увидел, что часть замечаний уже устранена далее (извините, я немного отстаю от реальности) - объедините, пожалуйста, наработки этого PR с https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/493/files (вмержите 481_first_selenium_test в 485_selenium_test_statistic) - этот PR закроем

2024-02-20 14:06 UTC, closed without merging